package Presentacion.FactoriaPresentacion;

public enum Evento {

	// --------------------------------// VISTA PRINCIPAL
	// //--------------------------------//

	VISTA_PRINCIPAL,

	// -----------------------------------// PLATAFORMA
	// //----------------------------------//

	// PRINCIPAL
	PLATAFORMA,

	// ALTA PLATAFORMA
	ALTA_PLATAFORMA, RES_ALTA_PLATAFORMA_OK, RES_ALTA_PLATAFORMA_KO,

	// BAJA PLATAFORMA
	BAJA_PLATAFORMA, RES_BAJA_PLATAFORMA_OK, RES_BAJA_PLATAFORMA_KO,

	// MOSTRAR PLATAFORMA
	MOSTRAR_PLATAFORMA, RES_MOSTRAR_PLATAFORMA_OK, RES_MOSTRAR_PLATAFORMA_KO,

	// MOSTRAR TODAS LAS PLATAFORMAS
	MOSTRAR_ALL_PLATAFORMAS, RES_MOSTRAR_ALL_PLATAFORMAS_OK, RES_MOSTRAR_ALL_PLATAFORMAS_KO,

	// MODIFICAR PLATAFORMA
	MODIFICAR_PLATAFORMA, RES_MODIFICAR_PLATAFORMA_OK, RES_MODIFICAR_PLATAFORMA_KO, RES_MODIFICAR_PLATAFORMA_KO_NOID,
	RES_MODIFICAR_PLATAFORMA_KO_SAMENAME,

	// VISTAS DE PLATAFORMA
	VALTA_PLATAFORMA, VBAJA_PLATAFORMA, VMODIFICAR_PLATAFORMA, VMOSTRAR_PLATAFORMA, VMOSTRAR_ALL_PLATAFORMAS,

	// -------------------------------------// VENTA
	// //-------------------------------------//

	// PRINCIPAL
	VENTA,

	// ABRIR VENTA
	ABRIR_VENTA_NEGOCIO, RES_ABRIR_VENTA_OK, RES_ABRIR_VENTA_KO,

	// INSERTAR PRODUCTO EN VENTA
	INSERTAR_PP_EN_VENTA_NEGOCIO, RES_INSERTAR_PP_EN_VENTA_OK, RES_INSERTAR_PP_EN_VENTA_KO,

	// ELIMINAR PRODUCTO EN VENTA
	ELIMINAR_PP_EN_VENTA_NEGOCIO, RES_ELIMINAR_PP_EN_VENTA_OK, RES_ELIMINAR_PP_EN_VENTA_KO,

	// CERRAR VENTA
	CERRAR_VENTA_NEGOCIO, RES_CERRAR_VENTA_OK, RES_CERRAR_VENTA_KO,

	// BUSCAR VENTA
	BUSCAR_VENTA_NEGOCIO, RES_BUSCAR_VENTA_OK, RES_BUSCAR_VENTA_KO,

	// MODIFICAR VENTA
	MODIFICAR_VENTA_NEGOCIO, RES_MODIFICAR_VENTA_OK, RES_MODIFICAR_VENTA_KO,

	// LISTAR VENTAS
	LISTAR_VENTAS_ALL_NEGOCIO, RES_LISTAR_VENTAS_ALL_OK, RES_LISTAR_VENTAS_ALL_KO,

	// LISTAR VENTAS POR TRABAJADOR
	LISTAR_VENTAS_X_TRABAJADOR_NEGOCIO, RES_LISTAR_VENTAS_X_TRABAJADOR_OK, RES_LISTAR_VENTAS_X_TRABAJADOR_KO,

	// LISTAR VENTAS POR PRODUCTO EN PLATAFORMA
	LISTAR_VENTAS_X_PRODUCTO_EN_PLATAFORMA_NEGOCIO, RES_LISTAR_VENTAS_X_PRODUCTO_EN_PLATAFORMA_OK,
	RES_LISTAR_VENTAS_X_PRODUCTO_EN_PLATAFORMA_KO,

	// DEVOLVER VENTA
	DEVOLVER_VENTA_NEGOCIO, RES_DEVOLVER_VENTA_OK, RES_DEVOLVER_VENTA_KO,

	// BAJA VENTA
	BAJA_VENTA_NEGOCIO, RES_BAJA_VENTA_OK, RES_BAJA_VENTA_KO,

	// QUERY VENTA
	CALCULAR_TOTAL_POR_PRODUCTOPLATAFORMA_QUERY, RES_CALCULAR_TOTAL_POR_PRODUCTOPLATAFORMA_QUERY_OK,
	RES_CALCULAR_TOTAL_POR_PRODUCTOPLATAFORMA_QUERY_KO,

	// VISTAS DE VENTA
	ABRIR_VENTA_VISTA, INSERTAR_PP_EN_VENTA_VISTA, ELIMINAR_PP_EN_VENTA_VISTA, CERRAR_VENTA_VISTA, BUSCAR_VENTA_VISTA,
	MODIFICAR_VENTA_VISTA, LISTAR_VENTAS_ALL_VISTA, CALCULAR_TOTAL_POR_PRODUCTOPLATAFORMA_QUERY_VISTA,
	LISTAR_VENTAS_X_TRABAJADOR_VISTA, LISTAR_VENTAS_X_PRODUCTO_EN_PLATAFORMA_VISTA, DEVOLVER_VENTA_VISTA,
	BAJA_VENTA_VISTA,

	// CARRITO
	PASAR_CARRITO_A_INSERTAR, RES_PASAR_CARRITO_A_INSERTAR_OK, RES_PASAR_CARRITO_A_INSERTAR_KO,

	PASAR_CARRITO_A_ELIMINAR, RES_PASAR_CARRITO_A_ELIMINAR_OK, RES_PASAR_CARRITO_A_ELIMINAR_KO,

	PASAR_CARRITO_A_CERRAR, RES_PASAR_CARRITO_A_CERRAR_OK, RES_PASAR_CARRITO_A_CERRAR_KO,
//	RES_PASAR_CARRITO_OK,
//	RES_PASAR_CARRITO_KO,

	// -----------------------------// PRODUCTO EN PLATAFORMA
	// //----------------------------//

	// PRINCIPAL
	PRODUCTO_EN_PLATAFORMA,

	// ALTA PRODUCTO EN PLATAFORMA
	ALTA_PRODUCTO_PLATAFORMA, RES_ALTA_PRODUCTO_PLATAFORMA_OK, RES_ALTA_PRODUCTO_PLATAFORMA_KO,

	// BAJA PRODUCTO EN PLATAFORMA
	BAJA_PRODUCTO_PLATAFORMA, RES_BAJA_PRODUCTO_PLATAFORMA_OK, RES_BAJA_PRODUCTO_PLATAFORMA_KO,

	// MODIFICAR PRODUCTO EN PLATAFORMA
	MODIFICAR_PRODUCTO_PLATAFORMA, RES_MODIFICAR_PRODUCTO_PLATAFORMA_OK, RES_MODIFICAR_PRODUCTO_PLATAFORMA_KO,

	// BUSCAR PRODUCTO EN PLATAFORMA
	BUSCAR_PRODUCTO_PLATAFORMA, RES_BUSCAR_PRODUCTO_PLATAFORMA_OK, RES_BUSCAR_PRODUCTO_PLATAFORMA_KO,

	// LISTAR TODOS PRODUCTO EN PLATAFORMA
	LISTAR_PRODUCTO_PLATAFORMA_ALL, RES_LISTAR_PRODUCTO_PLATAFORMA_ALL_OK, RES_LISTAR_PRODUCTO_PLATAFORMA_ALL_KO,

	// LISTAR PRODUCTO EN PLATAFORMA POR PLATAFORMA
	LISTAR_PP_X_PLATAFORMA, RES_LISTAR_PP_X_PLATAFORMA_OK, RES_LISTAR_PP_X_PLATAFORMA_KO,

	// LISTAR PRODUCTO EN PLATAFORMA POR PRODUCTO
	LISTAR_PP_X_PRODUCTO, RES_LISTAR_PP_X_PRODUCTO_OK, RES_LISTAR_PP_X_PRODUCTO_KO,

	// CALCULAR CANTIDAD PRODUCTO EN PLATAFORMA
	CALCULAR_CANTIDAD_PRODUCTO_EN_PLATAFORMA, RES_CALCULAR_CANTIDAD_PRODUCTO_EN_PLATAFORMA_OK,
	RES_CALCULAR_CANTIDAD_PRODUCTO_EN_PLATAFORMA_KO,

	// VISTAS DE PRODUCTO EN PLATAFORMA
	VLISTAR_TODO_PP, VALTA_PRODUCTO_PLATAFORMA, VBAJA_PRODUCTO_PLATAFORMA, VMODIFICAR_PRODUCTO_PLATAFORMA,
	VBUSCAR_PRODUCTO_PLATAFORMA, VCALCULAR_CANTIDAD_PRODUCTO_EN_PLATAFORMA,

	// -----------------------------------// TRABAJADOR
	// //----------------------------------//

	// PRINCIPAL
	TRABAJADOR,

	// ALTA TRABAJADOR
	ALTA_TRABAJADOR, RES_ALTA_TRABAJADOR_OK, RES_ALTA_TRABAJADOR_KO,

	// BAJA TRABAJADOR
	BAJA_TRABAJADOR, RES_BAJA_TRABAJADOR_OK, RES_BAJA_TRABAJADOR_KO,

	// BUSCAR TRABAJADOR
	BUSCAR_TRABAJADOR, RES_BUSCAR_TRABAJADOR_OK, RES_BUSCAR_TRABAJADOR_KO,

	// MODIFICAR TRABAJADOR
	MODIFICAR_TRABAJADOR, RES_MODIFICAR_TRABAJADOR_OK, RES_MODIFICAR_TRABAJADOR_KO,

	// LISTAR TRABAJADOR POR HABILIDAD
	LISTAR_TRABAJADOR_X_HABILIDAD, RES_LISTAR_TRABAJADOR_X_HABILIDAD_OK, RES_LISTAR_TRABAJADOR_X_HABILIDAD_KO,

	// LISTAR TRABAJADOR POR TIPO
	LISTAR_TRABAJADOR_X_TIPO, RES_LISTAR_TRABAJADOR_X_TIPO_SUPERVISOR_OK, RES_LISTAR_TRABAJADOR_X_TIPO_VENDEDOR_OK,
	RES_LISTAR_TRABAJADOR_X_TIPO_KO,

	// LISTAR TODOS LOS TRABAJADORES
	LISTAR_TRABAJADOR_ALL, RES_LISTAR_TRABAJADOR_ALL_OK, RES_LISTAR_TRABAJADOR_ALL_KO,

	// VINCULAR HABILIDAD A TRABAJADOR
	VINCULAR_HABILIDAD_TRABAJADOR, RES_VINCULAR_HABILIDAD_TRABAJADOR_OK, RES_VINCULAR_HABILIDAD_TRABAJADOR_KO,

	// DESVINCULAR HABILIDAD A TRABAJADOR
	DESVINCULAR_HABILIDAD_TRABAJADOR, RES_DESVINCULAR_HABILIDAD_TRABAJADOR_OK, RES_DESVINCULAR_HABILIDAD_TRABAJADOR_KO,

	// VISTAS DE TRABAJADOR
	VALTA_TRABAJADOR, VBAJA_TRABAJADOR, VMODIFICAR_TRABAJADOR, VMOSTRAR_TRABAJADOR, VMOSTRAR_ALL_TRABAJADOR,
	VMOSTRAR_TRABAJADOR_X_HABILIDAD, VVINCULAR_HABILIDAD_TRABAJADOR, VDESVINCULAR_HABILIDAD_TRABAJADOR,
	VBUSCAR_TRABAJADOR_X_TIPO,

	// -----------------------------------// HABILIDAD
	// //-----------------------------------//

	HABILIDAD,

	// ALTA HABILIDAD
	ALTA_HABILIDAD,
//	NALTA_HABILIDAD,
	RES_ALTA_HABILIDAD_OK, RES_ALTA_HABILIDAD_KO,

	// BAJA HABILIDAD
	BAJA_HABILIDAD,
//	NBAJA_HABILIDAD,
	RES_BAJA_HABILIDAD_OK, RES_BAJA_HABILIDAD_KO,

	// BUSCAR HABILIDAD
	BUSCAR_HABILIDAD,
//	NBUSCAR_HABILIDAD,
	RES_BUSCAR_HABILIDAD_OK, RES_BUSCAR_HABILIDAD_KO,

	// MODIFICAR HABILIDAD
	MODIFICAR_HABILIDAD,
//	NMODIFICAR_HABILIDAD,
	RES_MODIFICAR_HABILIDAD_OK, RES_MODIFICAR_HABILIDAD_KO, RES_MODIFICAR_HABILIDAD_KONOID,
	RES_MODIFICAR_HABILIDAD_KOSAMENAME,

	// LISTAR TODAS LAS HABILIDADES
	LISTAR_HABILIDAD_ALL,
//	NLISTAR_ALL_HABILIDAD,
	RES_LISTAR_HABILIDAD_ALL_OK, RES_LISTAR_HABILIDAD_ALL_KO,

	// LISTAR HABILIDADES DEL TRABAJADOR
	LISTAR_HABILIDAD_DEL_TRABAJADOR, RES_LISTAR_HABILIDAD_DEL_TRABAJADOR_OK, RES_LISTAR_HABILIDAD_DEL_TRABAJADOR_KO,

	// VISTAS DE HABILIDAD
	VALTA_HABILIDAD, VBAJA_HABILIDAD, VBUSCAR_HABILIDAD, VMODIFICAR_HABILIDAD, VLISTAR_HABILIDAD_ALL,
	VLISTAR_HABILIDAD_DEL_TRABAJADOR,

//	MOSTRAR_HABILIDAD,
//	NMOSTRAR_HABILIDAD,
//	MOSTRAR_ALL_HABILIDAD,
//	MOSTRAR_ALL_HABILIDAD_BY_WORKER,
//	NMOSTRAR_ALL_HABILIDAD_BY_WORKER,
//	RES_MOSTRAR_HABILIDAD_KO,
//	RES_MOSTRAR_HABILIDAD_OK,
//	RES_MOSTRAR_ALL_HABILIDAD_OK,
//	RES_MOSTRAR_ALL_HABILIDAD_KO,
//	RES_MOSTRAR_HABILIDAD_BY_WORKER_KO,
//	RES_MOSTRAR_HABILIDAD_BY_WORKER_OK,
//	RES_MODIFICAR_HABILIDAD_KONOID,
//	RES_MODIFICAR_HABILIDAD_KOSAMENAME,

//------------------------------------// PRODUCTO //-----------------------------------//

	// PRINCIPAL
	PRODUCTO,

	// ALTA PRODUCTO
	ALTA_PRODUCTO, RES_ALTA_PRODUCTO_OK, RES_ALTA_PRODUCTO_KO,

	// BAJA PRODUCTO
	BAJA_PRODUCTO, RES_BAJA_PRODUCTO_OK, RES_BAJA_PRODUCTO_KO,

	// MODIFICAR PRODUCTO
	MODIFICAR_PRODUCTO, RES_MODIFICAR_PRODUCTO_OK, RES_MODIFICAR_PRODUCTO_KO,

	// BUSCAR PRODUCTO
	BUSCAR_PRODUCTO, RES_BUSCAR_PRODUCTO_OK, RES_BUSCAR_PRODUCTO_KO,

	// LISTAR TODOS LOS PRODUCTOS
	LISTAR_PRODUCTO_ALL, RES_LISTAR_PRODUCTO_ALL_OK, RES_LISTAR_PRODUCTO_ALL_KO,

	// LISTAR PRODUCTOS POR TIPO
	LISTAR_PRODUCTOS_X_TIPO, RES_LISTAR_PRODUCTOS_X_TIPO_OK, RES_LISTAR_PRODUCTOS_X_TIPO_KO,

	// VISTAS DE PRODUCTO
	VALTA_PRODUCTO, VBAJA_PRODUCTO, VMODIFICAR_PRODUCTO, VBUSCAR_PRODUCTO, VLISTAR_PRODUCTO_ALL,
	VLISTAR_PRODUCTOS_X_TIPO,

	// -------------------------------------//
	// ALQUILER//-------------------------------------//

	// PRINCIPAL
	ALQUILER,

	// ABRIR ALQUILER
	ABRIR_ALQUILER_NEGOCIO, RES_ABRIR_ALQUILER_OK, RES_ABRIR_ALQUILER_KO,

	// INSERTAR PRODUCTO EN ALQUILER
	INSERTAR_MAQUINA_EN_ALQUILER_NEGOCIO, RES_INSERTAR_MAQUINA_EN_ALQUILER_OK, RES_INSERTAR_MAQUINA_EN_ALQUILER_KO,

	// ELIMINAR PRODUCTO EN ALQUILER
	ELIMINAR_MAQUINA_EN_ALQUILER_NEGOCIO, RES_ELIMINAR_MAQUINA_EN_ALQUILER_OK, RES_ELIMINAR_MAQUINA_EN_ALQUILER_KO,

	// CERRAR ALQUILER
	CERRAR_ALQUILER_NEGOCIO, RES_CERRAR_ALQUILER_OK, RES_CERRAR_ALQUILER_KO, RES_CERRAR_ALQUILER_KO_NOEMPLEADO,
	RES_CERRAR_ALQUILER_KO_NOCLIENTE, RES_CERRAR_ALQUILER_KO_CARRITO_VACIO,

	// BUSCAR ALQUILER
	BUSCAR_ALQUILER_NEGOCIO, RES_BUSCAR_ALQUILER_OK, RES_BUSCAR_ALQUILER_KO,

	// MODIFICAR ALQUILER
	MODIFICAR_ALQUILER_NEGOCIO, RES_MODIFICAR_ALQUILER_OK, RES_MODIFICAR_ALQUILER_KO,
	RES_MODIFICAR_ALQUILER_KO_NOCLIENTE, RES_MODIFICAR_ALQUILER_KO_NOEMPLEADO, RES_MODIFICAR_ALQUILER_KO_NOALQUILER,

	// LISTAR ALQUILERES
	LISTAR_ALQUILERES_ALL_NEGOCIO, RES_LISTAR_ALQUILERES_ALL_OK, RES_LISTAR_ALQUILERES_ALL_KO,

	// LISTAR ALQUILERES POR EMPLEADO
	LISTAR_ALQUILERES_X_EMPLEADO_NEGOCIO, RES_LISTAR_ALQUILERES_X_EMPLEADO_OK, RES_LISTAR_ALQUILERES_X_EMPLEADO_KO,

	// LISTAR ALQUILERES POR CLIENTE
	LISTAR_ALQUILERES_X_CLIENTE_NEGOCIO, RES_LISTAR_ALQUILERES_X_CLIENTE_OK, RES_LISTAR_ALQUILERES_X_CLIENTE_KO,

	// CANCELAR ALQUILER
	CANCELAR_ALQUILER_NEGOCIO, RES_CANCELAR_ALQUILER_OK, RES_CANCELAR_ALQUILER_KO_NO_ALQUILER,
	RES_CANCELAR_ALQUILER_KO_NO_LINEA_ALQUILER, RES_CANCELAR_ALQUILER_KO_MAQUINA_YA_DEVUELTA,
	RES_CANCELAR_ALQUILER_KO_MAQUINA_NO_ENCONTRADA, RES_CANCELAR_AQUILER_KO_ALQUILER_NO_ACTIVO,

	// BAJA ALQUILER
	BAJA_ALQUILER_NEGOCIO, RES_BAJA_ALQUILER_OK, RES_BAJA_ALQUILER_KO,

	// VISTAS DE ALQUILER
	ABRIR_ALQUILER_VISTA, INSERTAR_MAQUINA_EN_ALQUILER_VISTA, ELIMINAR_MAQUINA_EN_ALQUILER_VISTA, CERRAR_ALQUILER_VISTA,
	BUSCAR_ALQUILER_VISTA, MODIFICAR_ALQUILER_VISTA, LISTAR_ALQUILERES_ALL_VISTA, LISTAR_ALQUILERES_X_EMPLEADO_VISTA,
	LISTAR_ALQUILERES_X_CLIENTE_VISTA, CANCELAR_ALQUILER_VISTA, BAJA_ALQUILER_VISTA,

	// CARRITO
	PASAR_CARRITO_ALQUILER_A_INSERTAR, RES_PASAR_CARRITO_ALQUILER_A_INSERTAR_OK,
	RES_PASAR_CARRITO_ALQUILER_A_INSERTAR_KO,

	PASAR_CARRITO_ALQUILER_A_ELIMINAR, RES_PASAR_CARRITO_ALQUILER_A_ELIMINAR_OK,
	RES_PASAR_CARRITO_ALQUILER_A_ELIMINAR_KO,

	PASAR_CARRITO_ALQUILER_A_CERRAR, RES_PASAR_CARRITO_ALQUILER_A_CERRAR_OK, RES_PASAR_CARRITO_ALQUILER_A_CERRAR_KO,

	// -------------------------------------// CLIENTE
	// //-------------------------------------//

	// PRINCIPAL
	CLIENTE,

	// ALTA CLIENTE
	ALTA_CLIENTE, RES_ALTA_CLIENTE_OK, RES_ALTA_CLIENTE_KO,

	// BAJA CLIENTE
	BAJA_CLIENTE, RES_BAJA_CLIENTE_OK, RES_BAJA_CLIENTE_KO,

	// BUSCAR CLIENTE
	BUSCAR_CLIENTE, RES_BUSCAR_CLIENTE_OK, RES_BUSCAR_CLIENTE_KO,

	// MODIFICAR CLIENTE
	MODIFICAR_CLIENTE, RES_MODIFICAR_CLIENTE_OK, RES_MODIFICAR_CLIENTE_KO,

	// LISTAR TODOS LOS CLIENTES
	LISTAR_CLIENTES_ALL, RES_LISTAR_CLIENTES_ALL_OK, RES_LISTAR_CLIENTES_ALL_KO,

	// VISTAS DE CLIENTE
	VALTA_CLIENTE, VBAJA_CLIENTE, VMODIFICAR_CLIENTE, VBUSCAR_CLIENTE, VLISTAR_CLIENTES_ALL,

	// -------------------------------------// PROVEEDOR
	// //-------------------------------------//

	// PRINCIPAL
	PROVEEDOR,

	// ALTA PROVEEDOR
	ALTA_PROVEEDOR_NEGOCIO, RES_ALTA_PROVEEDOR_OK, RES_ALTA_PROVEEDOR_KO,

	// BAJA PROVEEDOR
	BAJA_PROVEEDOR_NEGOCIO, RES_BAJA_PROVEEDOR_OK, RES_BAJA_PROVEEDOR_KO,

	// BUSCAR PROVEEDOR
	BUSCAR_PROVEEDOR_NEGOCIO, RES_BUSCAR_PROVEEDOR_OK, RES_BUSCAR_PROVEEDOR_KO,

	// MODIFICAR PROVEEDOR
	MODIFICAR_PROVEEDOR_NEGOCIO, RES_MODIFICAR_PROVEEDOR_OK, RES_MODIFICAR_PROVEEDOR_KO,

	// LISTAR TODOS LOS PROVEEDORES
	LISTAR_PROVEEDORES_ALL_NEGOCIO, RES_LISTAR_PROVEEDORES_ALL_OK, RES_LISTAR_PROVEEDORES_ALL_KO,

	// LISTAR PROVEEDOR POR MODELO
	LISTAR_PROVEEDORES_MODELO_ALL_NEGOCIO, RES_LISTAR_PROVEEDORES_MODELO_ALL_OK, RES_LISTAR_PROVEEDORES_MODELO_ALL_KO,

	// VISTAS DE PROVEEDOR
	ALTA_PROVEEDOR_VISTA, BAJA_PROVEEDOR_VISTA, MODIFICAR_PROVEEDOR_VISTA, BUSCAR_PROVEEDOR_VISTA,
	LISTAR_PROVEEDOR_ALL_VISTA, LISTAR_PROVEEDOR_MODELO_ALL_VISTA,

	// -------------------------------------//
	// MODELO//-------------------------------------//

	// PRINCIPAL
	MODELO,

	// ALTA MODELO
	ALTA_MODELO_NEGOCIO, RES_ALTA_MODELO_OK, RES_ALTA_MODELO_KO,

	// BAJA MODELO
	BAJA_MODELO_NEGOCIO, RES_BAJA_MODELO_OK, RES_BAJA_MODELO_KO, RES_BAJA_MODELO_MAQUINAS_ACTIVAS_KO,
	RES_BAJA_MODELO_VINCULACIONES_PROVEEDOR_KO,

	// BUSCAR MODELO
	BUSCAR_MODELO_NEGOCIO, RES_BUSCAR_MODELO_OK, RES_BUSCAR_MODELO_KO,

	// MODIFICAR MODELO
	MODIFICAR_MODELO_NEGOCIO, RES_MODIFICAR_MODELO_OK, RES_MODIFICAR_MODELO_KO,

	// LISTAR TODOS LOS MODELOS
	LISTAR_MODELO_ALL_NEGOCIO, RES_LISTAR_MODELO_ALL_OK, RES_LISTAR_MODELO_ALL_KO,

	// LISTAR MODELOS POR PROVEEDOR
	LISTAR_MODELO_X_PROVEEDOR_NEGOCIO, RES_LISTAR_MODELO_X_PROVEEDOR_OK, RES_LISTAR_MODELO_X_PROVEEDOR_KO,

	// CUALQUIERA DE LOS "LISTAR" DEVUELVE LISTA VACÍA (FUNCIONA PARA LISTAR "ToDO"
	// COMO PARA LISTAR POR PROVEEDOR)
	RES_LISTAR_MODELO_OK_VACIO,

	// CALCULAR COSTE SEGURO MODELO
	CALCULAR_COSTE_SEGURO_MODELO_NEGOCIO, RES_CALCULAR_COSTE_SEGURO_MODELO_OK, RES_CALCULAR_COSTE_SEGURO_MODELO_KO,

	// VINCULAR PROVEEDOR A MODELO
	VINCULAR_PROVEEDOR_MODELO_NEGOCIO, RES_VINCULAR_PROVEEDOR_MODELO_OK, RES_VINCULAR_PROVEEDOR_MODELO_KO,

	// DESVINCULAR PROVEEDOR A MODELO
	DESVINCULAR_PROVEEDOR_MODELO_NEGOCIO, RES_DESVINCULAR_PROVEEDOR_MODELO_OK, RES_DESVINCULAR_PROVEEDOR_MODELO_KO,

	// VISTAS DE MODELO
	ALTA_MODELO_VISTA, BAJA_MODELO_VISTA, BUSCAR_MODELO_VISTA, MODIFICAR_MODELO_VISTA, LISTAR_MODELO_ALL_VISTA,
	LISTAR_MODELO_X_PROVEEDOR_VISTA, CALCULAR_COSTE_SEGURO_MODELO_VISTA, VINCULAR_PROVEEDOR_MODELO_VISTA,
	DESVINCULAR_PROVEEDOR_MODELO_VISTA,

	// -------------------------------------//
	// MAQUINA//-------------------------------------//

	// MAQUINA
	MAQUINA,

	// ALTA MAQUINA
	ALTA_MAQUINA_NEGOCIO, RES_ALTA_MAQUINA_OK, RES_ALTA_MAQUINA_KO,

	// BAJA MAQUINA
	BAJA_MAQUINA_NEGOCIO, RES_BAJA_MAQUINA_OK, RES_BAJA_MAQUINA_KO,

	// MODIFICAR MAQUINA
	MODIFICAR_MAQUINA_NEGOCIO, RES_MODIFICAR_MAQUINA_OK, RES_MODIFICAR_MAQUINA_KO,

	// BUSCAR MAQUINA
	BUSCAR_MAQUINA_NEGOCIO, RES_BUSCAR_MAQUINA_OK, RES_BUSCAR_MAQUINA_KO,

	// LISTAR MAQUINAS
	LISTAR_MAQUINAS_ALL_NEGOCIO, RES_LISTAR_MAQUINAS_ALL_OK, RES_LISTAR_MAQUINAS_ALL_KO,

	// LISTAR MAQUINAS POR MODELO
	LISTAR_MAQUINAS_X_MODELO_NEGOCIO, RES_LISTAR_MAQUINAS_X_MODELO_OK, RES_LISTAR_MAQUINAS_X_MODELO_KO,

	// VISTAS MAQUINA
	ALTA_MAQUINA_VISTA, BAJA_MAQUINA_VISTA, MODIFICAR_MAQUINA_VISTA, BUSCAR_MAQUINA_VISTA, LISTAR_MAQUINAS_ALL_VISTA,
	LISTAR_MAQUINAS_X_MODELO_VISTA,

	// -----------------------------// EMPLEADO
	// //-------------------------------------//

	// PRINCIPAL
	EMPLEADO,

	// ALTA EMPLEADO
	ALTA_EMPLEADO, RES_ALTA_EMPLEADO_OK, RES_ALTA_EMPLEADO_KO,

	// BAJA EMPLEADO
	BAJA_EMPLEADO, RES_BAJA_EMPLEADO_OK, RES_BAJA_EMPLEADO_KO,

	// BUSCAR EMPLEADO
	BUSCAR_EMPLEADO, RES_BUSCAR_EMPLEADO_OK, RES_BUSCAR_EMPLEADO_KO,

	// MODIFICAR EMPLEADO
	MODIFICAR_EMPLEADO, RES_MODIFICAR_EMPLEADO_OK, RES_MODIFICAR_EMPLEADO_KO,

	// LISTAR EMPLEADO
	LISTAR_EMPLEADO_ALL, RES_LISTAR_EMPLEADO_ALL_OK, RES_LISTAR_EMPLEADO_ALL_OK_VACIO, RES_LISTAR_EMPLEADO_ALL_KO,

	// VISTAS
	VALTA_EMPLEADO, VBAJA_EMPLEADO, VMODIFICAR_EMPLEADO, VBUSCAR_EMPLEADO, VLISTAR_EMPLEADO_ALL,

}